### ISSUE TITLE
Docker環境を用いてreactアプリケーションを動かす

### ISSUE THREAD

**Issue by Higakinn** [hgaiji/EDAR#1]
# 概要
Docker環境を用いてreactアプリケーションを動かせるようにする

# 必要ファイル
- Dockerfile
- docker-compose.yml
- [reactアプリケーションファイルなど]

# 完了条件
Dockerfile,docker-compose.ymlファイルを用いて、reactアプリケーションを動かせる

# 注意
- 不要なファイルはgit管理下にいれないこと(gitignoreを使う)
  -  npx create-react-app 時にgitignoreファイルは作成されるのでそれを使う

**Comment by Yuki-TU** [comment]
わかりません。

**Comment by Higakinn** [comment]
- Dockerfile 
```Dockerfile
FROM node:12.16.1

WORKDIR /usr/src/app/sample

COPY ./src/sample .
RUN yarn install
# COPY . .

# コンテナを起動する際に実行されるコマンド
ENTRYPOINT [ "yarn", "start" ]
```

- docker-compose.yml
```yaml
version: "3"
services:
  react:
    build:
      context: .
    tty: true
    volumes:
      - ./src/:/usr/src/app
    ports:
      - 3000:3000
```
